### ISSUE TITLE
mysql connection pool call select * query specific column value throw column not found exception

### ISSUE THREAD

**Issue by lzbjut** [database-mesh/pisanix#100]
## Bug Report
java.sql.SQLException: Column 'order_code' not found.

### What version of Pisanix are you using?
0.1.0

### What operating system and CPU are you using?
Linux,Kubernetes1.19.4

### Steps to reproduce
using multiple thread to trigger the query method
using hikari 3.3.0 to init conn pool and execute select * 
using preparedStatement and call getString method on a specific column

### What did you expect?
return the value of the specific column
### What did happened?
java.sql.SQLException: Column 'order_code' not found.

**Comment by xuanyuan300** [comment]
Currently, `pisa-proxy` will transparently transmit sql statements to the backend database, could you please provide us with captured packet using `tcpdump`.

**Comment by wbtlb** [comment]
fix in #73
