### ISSUE TITLE
Typo: typo in mysql_const.rs

### ISSUE THREAD

**Issue by CherishCai** [database-mesh/pisanix#102]
1. CACHING_SHA2PASSWORD_REQUEST_PUBLIC_KEY
https://github.com/database-mesh/pisanix/blob/2e4a7331b6469727a0b8c33c8d9512e7276105f6/pisa-proxy/protocol/mysql/src/mysql_const.rs#L244

2. Duplicate definition: LOCALINFILE_HEADER as LOCAL_IN_FILE_HEADER
https://github.com/database-mesh/pisanix/blob/2e4a7331b6469727a0b8c33c8d9512e7276105f6/pisa-proxy/protocol/mysql/src/mysql_const.rs#L23-L25

**Comment by mlycore** [comment]
Thanks ~
