### ISSUE TITLE
using pisa select on 5.6 MySQL throws Unknown system variable 'transaction_isolation' SQL exception

### ISSUE THREAD

**Issue by lzbjut** [database-mesh/pisanix#109]
### What version of Pisanix are you using?
0.1.0

### What operating system and CPU are you using?
Linux,Kubernetes1.19.4

### Steps to reproduce
using hikari 3.3.0 to init conn pool and execute select *
using preparedStatement and call getString method on a specific column
jdbc version：5.1.43 
MySQL version：5.6

### What did you expect?
get the column value

### What did happened?
throw an error ：Unknown system variable 'transaction_isolation'

**Comment by xuanyuan300** [comment]
1. The default protocol version is `5.7.37` returned by `pisa-proxy` , and your database version is 5.6.
2. `transaction_isolation` was added in MySQL 5.7.20. see https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_transaction_isolation.
Based on the above, Could you please try downgrade the jdbc driver version?

**Comment by wbtlb** [comment]
fix in #114
