### ISSUE TITLE
How to view observability page

### ISSUE THREAD

**Issue by lengyjc** [database-mesh/pisanix#122]
Whether there is an integrated indicator observation interface  or whether Grafana and Prometheus need to be installed to display the observation interface？

**Comment by xuanyuan300** [comment]
Currently, you need to configure `grafana` and `prometheus` yourself. `Pisa-Proxy` default metric-port is 8888

**Comment by mlycore** [comment]
The metrics are exposed through Pisa-Proxy's http port, it is defined in the annotation `database-mesh.io/metrics-port` as we discussed in #113 . The port will be setup to `5591` by default after v0.1.1.
