### ISSUE TITLE
Can't connect using mysql5.7 client

### ISSUE THREAD

**Issue by xuanyuan300** [database-mesh/pisanix#13]
### What version of Pisanix are you using?

master branch
### What operating system and CPU are you using?

system: Centos8
mysql client: 5.7.37
### What did you expect?
connect success
### What did happened?
connect hang
<img width="709" alt="image" src="https://user-images.githubusercontent.com/3368758/170687486-47ede2d4-7c96-4810-b70e-92183f171641.png">
<img width="714" alt="image" src="https://user-images.githubusercontent.com/3368758/170688310-1dd3b025-742e-415f-89a7-c7d3dbd793c5.png">

**Comment by wbtlb** [comment]
I will do some tests to review the bug you report.

**Comment by xuanyuan300** [comment]
I use centos:8 container to run pisa, can be connect success.

**Comment by xuanyuan300** [comment]
Cannot be reproduced. close
