### ISSUE TITLE
when database invalid, pisa-proxy start success, client connect success, but execute SQL error.

### ISSUE THREAD

**Issue by dongzl** [database-mesh/pisanix#131]
### Teachability, Documentation, Adoption, Migration Strategy:

when database invalid, pisa-proxy start success, client connect success, but execute SQL error. 

We can add database status check when start pisa-proxy.

**Comment by wbtlb** [comment]
Hi @dongzl 
Pisa-Proxy includes server protocol and client protocol. You can connect to Pisa-Proxy successed when it started correctly.However, if banckend database source is failed, Pisa-Proxy can't dispatch sql to backend database.
We will add connection check in the future work.

**Comment by mlycore** [comment]
Any updates on this ? or it will be closed if it is a stale one.
