### ISSUE TITLE
pisa-proxy get endpoint failed

### ISSUE THREAD

**Issue by wbtlb** [database-mesh/pisanix#145]
### What version of Pisanix are you using?

v0.1.1

### What did you expect?
get backend endpoint correctly.
### What did happened?
error log is as follows:
thread 'pisa-proxy' panicked at 'called `Option::unwrap()` on a `None` value', runtime/mysql/src/transaction_fsm.rs:340:43

**Comment by mlycore** [comment]
What's the test case?
