### ISSUE TITLE
feat(strategy): dynamic read write splitting

### ISSUE THREAD

**Issue by wbtlb** [database-mesh/pisanix#194]
## Development Task
# Description
Now，Pisa-Proxy has supported static read write splitting strategy. Static strategy depends on config, once datasource status is changed, Pisa-Proxy can't route SQL correctly. In dynamic read write splitting strategy, Pisa-Proxy will probe datasource status and reconcile loadbalance strategy dynamicly.

# Implement
In this version, Pisa-proxy will support MHA high availability strategy. Pisa-Proxy will spawn four kind of monitor to probe the status of datasource.The rules match module will fork a thread to recive loadbalance strategy from dynamic read write splitting module by channel.In this module, there are four kind of monitor to probe datasource status.
- Connect Monitor: probe the connectivity  of datasource.
- Ping Monitor: probe health status of datasource.
- Lag Monitor: probe the late time between master node and slave node.
- ReadOnly Monitor: probe the role of datasource.

### Future Design Chart
<img width="741" alt="image" src="https://user-images.githubusercontent.com/12859337/179657272-6027752a-aa94-4ba6-b0ae-64aafd592f85.png">

#### Glossary
- Monitor Reconcile: Monitor Reconcile. Get status from monitors and compute final read write splitting strategy.
- Discovery: The kind of discovery, like MHA,RDS,MGR etc.
- Monitor: The kind of Monitor, includes Connect Monitor, Ping Monitor, ReadOnly Monitor, Lag Monitor.

### Probe Flow
1. Start Monitor to probe datasource.
2. Probe the connectivity of Master node and Slave node.
3. If connectivity is ok.
    3.1. probe the role of datasource.
    3.2. probe the late time between master node and slave node.
        3.2.1. If slave node is not late from master node, enter next time probe.
        3.2.2. If slave node is late from master node, update the list of loadbalance and enter next time probe.
4. If connectivity is not ok.
    4.1. If probe slave change to master,start Lag probe.
        4.1.1. If slave node is not late from master node, enter next time probe.
        4.1.2. If slave node is late from master node, update the list of loadbalance and enter next time probe.
    4.2.If slave node is not change to master, enter next time probe. 

<img width="356" alt="image" src="https://user-images.githubusercontent.com/12859337/179657385-01a83350-b947-483a-83a3-1ece45de9409.png">

### Configuration
|param | type| required| default | description|
|-- | -- | -- | -- | --|
|user | string | yes | None | Monitor user name|
|password | string | yes | None | Monitor password|
|monitor_interval | u64 | yes | 5000 | The interval of `Reconcile Monitor `update strategy(millisecond)|
|connect_interval | u64 | yes | 60000 | The interval of `Connect Monitor` probe (millisecond)|
|connect_timeout | u64 | yes| 600 | The timeout of `Connect Monitor(`millisecond)|
|connect_max_failures | u64 | yes | 3 | The max failures times of `Connect Monitor` probe|
|ping_interval | u64 | yes | 8000 | The interval of `Ping Monitor ` probe(millisecond)|
|ping_timeout | u64 | yes | 1000 | The timeout of `Ping Monitor` probe(millisecond)|
|ping_max_failures | u64 | yes | 3 | The max failures times of `Ping Monitor` probe|
|replication_lag_interval | u64 | yes | 10000 | The interval of `Lag Monitor` probe(millisecond)|
|replication_lag_timeout | u64 | yes | 1000| The timeout of `Lag Monitor` probe(millisecond)|
|replication_lag_max_failures | u64 | yes | 1 | The max failures of `Lag Monitor` probe|
|max_replication_lag | u64 | yes | 10000 |The threshold of `Lag Monitor` probe(millisecond)|
|read_only_interval | u64 | yes | 3000 | The interval of `ReadOnly Monitor` probe(millisecond)|
|read_only_timeout | u64 | yes | 600| The timeout of `ReadOnly Monitor` probe(millisecond)|
|read_only_max_failures | u64 | yes | 3 |The max failures times of `ReadOnly Monitor` probe|

##### Configuration Structure
```
#[derive(Debug, Serialize, Deserialize, Clone, Default)]
pub struct ReadWriteSplitting {
    #[serde(rename = "static")]
    pub statics: Option<ReadWriteSplittingStatic>,
    pub dynamic: Option<ReadWriteSplitting>
}

#[derive(Debug, Serialize, Deserialize, Clone, Default)]
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ReadWriteSplittingDynamic {
    pub default_target: TargetRole,
    #[serde(rename = "rule")]
    pub rules: Vec<ReadWriteSplittingRule>,
    pub discovery: Discovery,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
#[serde(rename_all = "lowercase", tag="type")]
pub enum Discovery {
    Mha(ManagerHighAvailability),
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Default)]
pub struct ManagerHighAvailability {
    pub user: String,
    pub password: String,
    pub pool_size: Option<u8>,
    pub monitor_interval: u64,
    pub connect_interval: u64,
    pub connect_timeout: u64,
    pub connect_max_failures: u64,
    pub ping_interval: u64,
    pub ping_timeout: u64,
    pub ping_max_failures: u64,
    pub replication_lag_interval: u64,
    pub replication_lag_timeout: u64,
    pub replication_lag_max_failures: u64,
    pub max_replication_lag: u64,
    pub read_only_interval: u64,
    pub read_only_timeout: u64,
    pub read_only_max_failures: u64,
}
```

##### Configuration Example
```
[proxy.config.read_write_splitting]

[proxy.config.read_write_splitting.dynamic]
default_target = "readwrite"

[proxy.config.read_write_splitting.dynamic.discovery]
type = "mha"
user = "monitor"
password = "monitor"
pool_size = 16
monitor_interval = 1000
connect_interval = 2000
connect_timeout = 200
connect_max_failures = 3
ping_interval = 1000
ping_timeout = 100
ping_max_failures = 3
replication_lag_interval = 1000
replication_lag_timeout = 3
replication_lag_max_failures = 3
max_replication_lag = 3
read_only_interval = 1000
read_only_timeout = 3
read_only_max_failures = 3

[[proxy.config.read_write_splitting.dynamic.rule]]
name = "write-rule"
type = "regex"
regex = ["^insert"]
target = "readwrite"
algorithm_name = "roundrobin"

[[proxy.config.read_write_splitting.dynamic.rule]]
name = "read-rule"
type = "regex"
regex = ["^select"]
target = "read"
algorithm_name = "roundrobin"
```

#### Check List
- [x] Monitor Reconcile.
- [x] configuration.
- [ ] Pisa-Controller.
- [x] Rules Match dynamic update.
- [x] Connect Monitor.
- [x] Ping Monitor.
- [x] Lag Monitor.
- [x] ReadOnly Monitor.
- [x] com query raw parse. @xuanyuan300 

Association Issue #88

**Comment by mlycore** [comment]
For better understanding, we should use `period` instead of `interval`, using `failureThreshold` instead of MaxFailures`.
