### ISSUE TITLE
Dynamic read write splitting monitor support switch

### ISSUE THREAD

**Issue by wbtlb** [database-mesh/pisanix#226]
### Describe the feature you'd like:

In dynamic read write splitting,there are 4 kinds of monitor.They will start with Pisa-Proxy startup.Some time,maybe user doesn't need all of them,we could add a switch in monitor.User can start monitor they need.

**Comment by tuichenchuxin** [comment]
I want to try this :).

**Comment by wbtlb** [comment]
@tuichenchuxin assign to you.
