### ISSUE TITLE
unit test build error for mac 

### ISSUE THREAD

**Issue by zhang-arvin** [database-mesh/pisanix#253]
## Bug Report

error: This macro cannot be used on the current target.
                                   You can prevent it from being used in other architectures by
                                   guarding it behind a cfg(any(target_arch = "x86", target_arch = "x86_64")).
   --> parser/mysql/src/lex.rs:675:16
    |
675 |             if is_x86_feature_detected!("sse2") {
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in the macro `is_x86_feature_detected` (in Nightly builds, run with -Z macro-backtrace for more info)

### What operating system and CPU are you using?

<img width="286" alt="image" src="https://user-images.githubusercontent.com/31638790/183885986-9bad3b2a-a4ee-43c4-af91-8e8c11dfd3d6.png">

**Comment by xuanyuan300** [comment]
Thanks feeback, I will check it.

**Comment by mlycore** [comment]
It seems like `cfg!(any(target_arch = "x86", target_arch = "x86_64")) ` didn't exclude the target arch, I updated it with a general macro ` #[cfg(any(target_arch = "x86", target_arch = "x86_64"))]` and compiled successfully.

**Comment by mlycore** [comment]
@zhang-arvin Is this issue still reproducible ? This issue will be closed if it is fixed.
