### ISSUE TITLE
Count function merge failed

### ISSUE THREAD

**Issue by wbtlb** [database-mesh/pisanix#378]
### What version of Pisanix are you using?
pisanix v0.3.1

### Steps to reproduce
MySQL [mysqlio_test]> select count(\*) from t_order;
+----------+
| count(*) |
+----------+
|        1 |
|        1 |
+----------+

### What did you expect?
in Sharding, after count computing, result should be merged

**Comment by xuanyuan300** [comment]
I will check on it.
