### ISSUE TITLE
How to run pisa-proxy with the master branch code.

### ISSUE THREAD

**Issue by dongzl** [database-mesh/pisanix#81]
## Question

<img width="777" alt="image" src="https://user-images.githubusercontent.com/5917359/173182565-40bfc460-5078-4bae-b098-5f50ee809c02.png">

1. I create a config file at `pisa-proxy/ect/`.
2. `Cargo bulid` the code.
3. cd to `pisanix/pisa-proxy/target/debug` and execute `./proxy`.

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("pisa-controller.pisa-system")), port: Some(8080), path: "/apis/configs.database-mesh.io/v1alpha1/namespaces/default/proxyconfigs/default", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("dns error", Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })) }', app/config/src/config.rs:132:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by mlycore** [comment]
For example, if you already have a pisa-proxy config as `examples/example-config.toml`, then you could try following steps:
1. Run `make build` under pisa-proxy directory
2. Execute command as `LOCAL_CONFIG=true ../bin/proxy -c examples/example-config.toml`

**Comment by mlycore** [comment]
Thanks for your feedback, this lack of description will be soon updated to the documentations.

**Comment by mlycore** [comment]
Docs updated: https://www.pisanix.io/docs/UseCases/standalone
